services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    restart: unless-stopped
    privileged: true
    cap_add:
      - CAP_NET_BIND_SERVICE
    ports:
      - "443:443"
      - "443:443/udp"
      - "8443:8443"
      - "8443:8443/udp"
      - "8080:8080"
    volumes:
      - /var/log/sing-box:/var/log/sing-box:rw
      - /etc/localtime:/etc/localtime:ro
      - ./etc/config.json:/etc/sing-box/config.json:ro
      - ./geodata:/usr/local/share/sing-box
      - /etc/hysteria/tls/:/etc/hysteria/tls/:ro
    command: "run -c /etc/sing-box/config.json"
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # rotate when log reaches 10MB
        max-file: "3" # keep at most 3 rotated log files
